### ISSUE TITLE
Clicking cancel on Rave payment redirect page gives error

### ISSUE THREAD

**Issue by azizarnold** [Flutterwave/WHMCS-v2#17]
When customer opens invoice it redirects fine to the payment page and if customers pay all is well. But if customers click the cancel payment button the below error is returned.

ArgumentCountError: Too few arguments to function requery(), 0 passed in /home/my/domains/domain/public_html/modules/gateways/callback/rave.php on line 146 and exactly 1 expected in /home/my/domains/domain/public_html/modules/gateways/callback/rave.php:95
Stack trace:
#0 /home/my/domains/domain/public_html/modules/gateways/callback/rave.php(146): requery()
#1 /home/my/domains/domain/public_html/modules/gateways/callback/rave.php(92): requery()
#2 {main}

**Comment by azizarnold** [comment]
Seems to happen when you select "redirection" within the payment gateway settings. If you select Modal Inline it works fine.
