### ISSUE TITLE
error after cancelling payment in via invoice

### ISSUE THREAD

**Issue by azizarnold** [Flutterwave/WHMCS-v2#19]
ArgumentCountError: Too few arguments to function requery(), 0 passed in /home/my/domains/domain.com/public_html/modules/gateways/callback/rave.php on line 146 and exactly 1 expected in /home/my/domains/domain.com/public_html/modules/gateways/callback/rave.php:95
Stack trace:
#0 /home/my/domains/domain.com/public_html/modules/gateways/callback/rave.php(146): requery()
#1 /home/my/domains/domain.com/public_html/modules/gateways/callback/rave.php(92): requery()
#2 {main}

**Comment by azizarnold** [comment]
Seems to happen when you select "redirection" within the payment gateway settings. If you select Modal Inline it works fine.
